### ISSUE TITLE
Error when a player logs on to the server

### ISSUE THREAD

**Issue by MerLant** [Rosewood-Development/RoseChat#1]
Error when a player logs on to the server. The error is also written when the player is on the server. Waterfal ver #510

Error 
```
[02:35:33 WARN]: java.io.EOFException
[02:35:33 WARN]:        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:203)
[02:35:33 WARN]:        at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:614)
[02:35:33 WARN]:        at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:570)
[02:35:33 WARN]:        at RoseChat-Beta-6.jar//dev.rosewood.rosechat.listener.BungeeListener.onPluginMessageReceived(BungeeListener.java:58)
[02:35:33 WARN]:        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
[02:35:33 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3679)
[02:35:33 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInCustomPayload.a(PacketPlayInCustomPayload.java:37)
[02:35:33 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInCustomPayload.a(PacketPlayInCustomPayload.java:15)
[02:35:33 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[02:35:33 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[02:35:33 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[02:35:33 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[02:35:33 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1361)
[02:35:33 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
[02:35:33 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[02:35:33 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1338)
[02:35:33 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1331)
[02:35:33 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[02:35:33 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1309)
[02:35:33 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1197)
[02:35:33 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[02:35:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Vekhove** [comment]
Hi, this might already be resolved, but could you update to the latest version (https://jenkins.rosewooddev.io/job/Rosewood%20Development/job/RoseChat/9/artifact/build/libs/RoseChat-Beta-9.jar) and see if the error still occurs?

**Comment by Vekhove** [comment]
Closed due to inactivity / probably fixed.
Please join the support server if this happens again, or you have any more issues: https://discord.gg/MgUsTBK
